basic:
  seed: 42
  model_name: "cl-tohoku/bert-base-japanese"
  data_path: "your/data-path"
train:
  epoch: 3
  batch_size: 8
  lr: 0.0001
  weight_decay: 0.0001
  save_path: "src/pytorch_nlp/model/test_model.pth"
